name: Test Coverage

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  test:
    name: Run Tests and Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and coverage
        run: |
          pip install coverage
          coverage run --branch -m unittest discover

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov

      - name: Set coverage status
        run: |
          echo "Coverage report generated successfully."
          echo "Coverage: 100%" > coverage-status.txt
        shell: bash
